# Generated by Django 5.1.6 on 2025-02-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='student',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='status',
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
