# Generated by Django 5.1.6 on 2025-02-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_rename_student_progress_user_remove_progress_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.AlterField(
            model_name='progress',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
