# Generated by Django 5.1.6 on 2025-02-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_progress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='updated_at',
        ),
    ]
