# Generated by Django 5.1.6 on 2025-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_progress_created_at_progress_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
