# Generated by Django 5.1.6 on 2025-03-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_progress_user_alter_progress_question1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='game',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='question6',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
