# Generated by Django 5.1.6 on 2025-03-12 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_subpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='progress_note',
            new_name='progress_detail',
        ),
        migrations.RenameField(
            model_name='subpage',
            old_name='title',
            new_name='progress_title',
        ),
        migrations.RemoveField(
            model_name='subpage',
            name='design_document',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='subpage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.game'),
        ),
    ]
