# Generated by Django 5.1.6 on 2025-03-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0014_plan_gameplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplan',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='progress.plan'),
        ),
    ]
