# Generated by Django 5.1.6 on 2025-03-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0015_alter_gameplan_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='progress',
            name='description2',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='GamePlan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
