# Generated by Django 5.1.6 on 2025-03-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0016_rename_description_progress_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='test',
            field=models.TextField(default='test'),
        ),
    ]
