# Generated by Django 5.1.6 on 2025-03-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0017_game_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='test',
            field=models.TextField(default='test', max_length=200, verbose_name='test'),
        ),
    ]
