# Generated by Django 5.1.6 on 2025-03-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0018_alter_game_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='test',
            field=models.TextField(default='test', max_length=20, verbose_name='test'),
        ),
    ]
