# Generated by Django 5.1.6 on 2025-03-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0019_alter_game_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='test',
        ),
        migrations.AddField(
            model_name='game',
            name='description1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='description2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='description3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='description4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='description5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='overview',
            field=models.TextField(default=''),
        ),
    ]
