# Generated by Django 5.1.6 on 2025-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplan',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gameplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
