# Generated by Django 5.1.6 on 2025-03-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_gameplan_features_gameplan_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '実行中'), ('completed', '完了済み')], default='not_started', max_length=20)),
                ('game_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plans.gameplan')),
            ],
        ),
    ]
