# Generated by Django 5.1.6 on 2025-03-13 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='plans.gameplan')),
            ],
        ),
    ]
