# Generated by Django 5.1.6 on 2025-03-13 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='game_plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='plans.gameplan'),
        ),
    ]
