# Generated by Django 5.1.6 on 2025-03-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
