# Generated by Django 5.1.6 on 2025-03-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='gameplan',
            name='summary',
        ),
        migrations.AddField(
            model_name='gameplan',
            name='description1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gameplan',
            name='description2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gameplan',
            name='description3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gameplan',
            name='description4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gameplan',
            name='description5',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
