# Generated by Django 5.1.6 on 2025-03-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_remove_gameplan_features_remove_gameplan_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='content',
        ),
        migrations.AddField(
            model_name='feedback',
            name='question1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question6',
            field=models.TextField(default=''),
        ),
    ]
